[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base = "light"
primaryColor = "#9C7A4A"
backgroundColor = "#ECE7DC"
secondaryBackgroundColor = "#F3EFE6"
textColor = "#5B6470"
font = "serif"

[browser]
gatherUsageStats = false
